### ISSUE TITLE
Update this software.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [flathub/com.visualstudio.code.insiders#494]
Like http://github.com/flathub/com.visualstudio.code/issues/247, this software has not been updated recently.

**Comment by roke-julian-lockhart** [comment]
As of 2021-10-01, the least that are requiring review are:
http://github.com/flathub/com.visualstudio.code.insiders/pull/490
http://github.com/flathub/com.visualstudio.code.insiders/pull/485
http://github.com/flathub/com.visualstudio.code.insiders/pull/483
http://github.com/flathub/com.visualstudio.code.insiders/pull/479
http://github.com/flathub/com.visualstudio.code.insiders/pull/477
http://github.com/flathub/com.visualstudio.code.insiders/pull/472
http://github.com/flathub/com.visualstudio.code.insiders/pull/470
http://github.com/flathub/com.visualstudio.code.insiders/pull/466
http://github.com/flathub/com.visualstudio.code.insiders/pull/464
http://github.com/flathub/com.visualstudio.code.insiders/pull/462
http://github.com/flathub/com.visualstudio.code.insiders/pull/460
http://github.com/flathub/com.visualstudio.code.insiders/pull/454
http://github.com/flathub/com.visualstudio.code.insiders/pull/453
http://github.com/flathub/com.visualstudio.code.insiders/pull/449
http://github.com/flathub/com.visualstudio.code.insiders/pull/445
http://github.com/flathub/com.visualstudio.code.insiders/pull/439
http://github.com/flathub/com.visualstudio.code.insiders/pull/430
http://github.com/flathub/com.visualstudio.code.insiders/pull/428
http://github.com/flathub/com.visualstudio.code.insiders/pull/427
http://github.com/flathub/com.visualstudio.code.insiders/pull/417
http://github.com/flathub/com.visualstudio.code.insiders/pull/412
http://github.com/flathub/com.visualstudio.code.insiders/pull/410
http://github.com/flathub/com.visualstudio.code.insiders/pull/407
http://github.com/flathub/com.visualstudio.code.insiders/pull/406
http://github.com/flathub/com.visualstudio.code.insiders/pull/405
http://github.com/flathub/com.visualstudio.code.insiders/pull/402
http://github.com/flathub/com.visualstudio.code.insiders/pull/399
http://github.com/flathub/com.visualstudio.code.insiders/pull/396
http://github.com/flathub/com.visualstudio.code.insiders/pull/393
http://github.com/flathub/com.visualstudio.code.insiders/pull/385
http://github.com/flathub/com.visualstudio.code.insiders/pull/382
http://github.com/flathub/com.visualstudio.code.insiders/pull/280
http://github.com/flathub/com.visualstudio.code.insiders/pull/379
http://github.com/flathub/com.visualstudio.code.insiders/pull/376
http://github.com/flathub/com.visualstudio.code.insiders/pull/371
http://github.com/flathub/com.visualstudio.code.insiders/pull/353
http://github.com/flathub/com.visualstudio.code.insiders/pull/345
http://github.com/flathub/com.visualstudio.code.insiders/pull/343

**Comment by fooishbar** [comment]
It has been updated, it's just that not every PR quite makes it.

Have a look at the list of closed PRs (like [this one](https://github.com/flathub/com.visualstudio.code.insiders/pull/496)), or the list of commits.

**Comment by roke-julian-lockhart** [comment]
> http://github.com/flathub/com.visualstudio.code.insiders/issues/494#issuecomment-932315886.

Most of these are basic updates. At the very least, delete the pending pull requests that are for older versions of the debian package than what http://github.com/flathub/com.visualstudio.code.insiders/pull/490 is suggesting. Relegating this responsibility partially to the automatic rebot is not acceptable when so many important pull requests are not being merged.

**Comment by roke-julian-lockhart** [comment]
> http://github.com/flathub/com.visualstudio.code.insiders/issues/494#issuecomment-932316896.

I am very thankful that the pending requests are being managed properly. I shall cease communication via this issue thus, unless any more comments are posted to here.

**Comment by fooishbar** [comment]
Yes, they have all been closed.
