### ISSUE TITLE
"com.visualstudio.code.insiders" should become one branch of "com.visualstudio.code".

### ISSUE THREAD

**Issue by roke-julian-lockhart** [flathub/com.visualstudio.code.insiders#495]
"[com.visualstudio.code.insiders](http://github.com/flathub/com.visualstudio.code.insiders)" should be merged with "[com.visualstudio.code](http://github.com/flathub/com.visualstudio.code)" as one branch of "[com.visualstudio.code](http://github.com/flathub/com.visualstudio.code)" so that "[com.visualstudio.code.insiders](https://github.com/flathub/com.visualstudio.code.insiders)" shall be able to be invoked as "[`flatpak run com.visualstudio.code//insiders`](http://github.com/flathub/flathub/issues/1915#issue-734456405)".

"http://discourse.flathub.org/t/1710" may be relevant.

**Comment by roke-julian-lockhart** [comment]
The counterpart of this issue is available at "http://github.com/flathub/com.visualstudio.code/issues/256".

**Comment by fooishbar** [comment]
Closing for the same rationale as flathub/com.visualstudio.code#256.
