### ISSUE TITLE
Install code insiders via pop!_os 22.04

### ISSUE THREAD

**Issue by DaniloOPAvanade** [flathub/com.visualstudio.code.insiders#726]
error: The application com.visualstudio.code.insiders/x86_64/beta requires the runtime org.freedesktop.Sdk/x86_64/21.08 which was not found

**Comment by comigor** [comment]
I've just stumbled with the same problem. Using the `--user` flag in all commands solved it for me:
```
flatpak install --user org.freedesktop.Sdk/x86_64/21.08
flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install --user flathub-beta com.visualstudio.code.insiders
```

**Comment by bbhtt** [comment]
You have to install it first from the stable flathub repo like that. 

freedesktop sdk stable runtimes aren't pushed to the flathub beta repo, only beta SDKs are pushed there.
